services:
  suite:
    container_name: suite
    image: specmatic/enterprise:latest
    volumes:
      - ./:/usr/src/app
      - ../license.txt:/specmatic/specmatic-license.txt
    command: ["run-suite"]
