ProductBase:
  name:
  - Idly Vada
  - Garlic Nan
  - Margarita Pizza
ProductType:
- food
ProductInventory:
- 100
- 5
- 14
- 74
Id:
  id:
  - 1
  - 2
  - 3
OrderBase:
  productid:
    - 1
  count:
    - 10
BadRequest:
  timestamp:
    - 2025-06-12T12:00:00.000+00:00
  status:
    - 400
  path:
    - /products
PARAMETERS:
  HEADER:
    pageSize:
    - 10
  QUERY:
    type:
    - food
    from-date:
    - '2026-07-07'
    to-date:
    - '2026-07-09'
Product:
  id:
  - 2
  - 3
  - 1
  name:
  - Idly Vada
  - Garlic Nan
  - Margarita Pizza
  createdOn:
  - '2026-07-09'
