#!/bin/sh
set -eu

: "${BASIC_AUTH_TOKEN:?}"
: "${API_KEY:?}"
: "${KEYCLOAK_USER_USERNAME:?}"
: "${KEYCLOAK_USER_PASSWORD:?}"
: "${KEYCLOAK_SERVICE_ACCOUNT_USERNAME:?}"
: "${KEYCLOAK_SERVICE_ACCOUNT_PASSWORD:?}"
: "${VAULT_TOKEN:?}"

vault kv put secret/api-security-schemes \
  BASIC_AUTH_TOKEN="${BASIC_AUTH_TOKEN}" \
  API_KEY="${API_KEY}" \
  KEYCLOAK_USER_USERNAME="${KEYCLOAK_USER_USERNAME}" \
  KEYCLOAK_USER_PASSWORD="${KEYCLOAK_USER_PASSWORD}" \
  KEYCLOAK_SERVICE_ACCOUNT_USERNAME="${KEYCLOAK_SERVICE_ACCOUNT_USERNAME}" \
  KEYCLOAK_SERVICE_ACCOUNT_PASSWORD="${KEYCLOAK_SERVICE_ACCOUNT_PASSWORD}"

printf '%s' "${VAULT_TOKEN}" > /vault/agent-auth/token
chown 100:1000 /vault/agent-auth/token
chmod 0600 /vault/agent-auth/token
