openapi: 3.0.1
info:
  title: User API
  version: "1.0.0"
paths:
  /api/users/{id}:
    get:
      summary: Get user by id
      parameters:
        - $ref: "#/components/parameters/UserIdPathParam"
      responses:
        "200":
          $ref: "#/components/responses/User200"
components:
  parameters:
    UserIdPathParam:
      name: id
      in: path
      required: true
      schema:
        type: integer
  responses:
    User200:
      description: User found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/User"
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
